version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: appsignal
    versions:
    - 2.11.1
    - 2.11.5
  - dependency-name: rubocop
    versions:
    - 1.7.0
    - 1.9.0
  - dependency-name: brakeman
    versions:
    - 4.10.1
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
  - dependency-name: loofah
    versions:
    - 2.8.0
  - dependency-name: rake
    versions:
    - 13.0.1
